<?php

declare(strict_types=1);

return [
    'AMOUNT_PAGINATE_DEFAULT' => env('AMOUNT_PAGINATE_DEFAULT', 15),

    'COBRANCA_JUROS_DIARIO' => env('COBRANCA_JUROS_DIARIO', 1.0),
    'COBRANCA_MULTA_PERCENTUAL' => env('COBRANCA_MULTA_PERCENTUAL', 2.0),
];
